name: Discord Notification

on:
  pull_request:
    types: [opened, reopened] 

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          WEBHOOK_URL: ${{ secrets.https://discord.com/api/webhooks/1223682097173237850/PALbrFVVzjEyeZwQ8fE_QRlAI5BRSj1gIaDr3tLBBLfXPK-oQ7JuPA676tL3oMQLmLDK }} # Збережіть URL вебхуку в секретах вашого репозиторію
        run: |
          curl -H "Content-Type: application/json" -d '{"content":"New pull request created!"}' -X POST $https://discord.com/api/webhooks/1223682097173237850/PALbrFVVzjEyeZwQ8fE_QRlAI5BRSj1gIaDr3tLBBLfXPK-oQ7JuPA676tL3oMQLmLDK
