name: Branch Protection

on:
  push:
    branches:
      - main
      - develop

jobs:
  protect-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Protect main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Protect develop branch
        uses: actions/checkout@v2
        with:
          ref: develop
